[package]
name = "mesalink"
version = "1.0.0-cratesio"
edition = "2018"
authors = ["The MesaLink Project Contributors"]
license = "BSD-3-Clause"
readme = "README.md"
description = "MesaLink is a memory-safe and OpenSSL-compatible TLS library based on Rustls and Ring."
keywords = ["tls", "ssl", "rust"]
homepage = "https://github.com/mesalock-linux/mesalink"
repository = "https://github.com/mesalock-linux/mesalink"
categories = ["network-programming"]
build = "build.rs"

[badges]
travis-ci = { repository = "mesalock-linux/mesalink", branch = "master"  }

[lib]
name = "mesalink"
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = ["client_apis", "server_apis", "error_strings", "tls13", "aesgcm", "chachapoly", "x25519", "ecdh", "ecdsa", "verifier"]
forked_deps = []
client_apis = []
server_apis = []
error_strings = []
tls13 = []
aesgcm = []
chachapoly = []
x25519 = []
ecdh = []
ecdsa = []
verifier = ["rustls/dangerous_configuration"]
nightly = []
jemalloc_allocator = ["jemallocator"]

[dependencies]
rustls = "0.16.0"
webpki = "0.21.0"
webpki-roots = "0.17.0"
sct = "0.6.0"
ring = "0.16"
untrusted = "0.7"
env_logger = "0.6"
libc = "0.2"
lazy_static = "1.0"
enum_to_u8_slice_derive = "0.1"
bitflags = "1.0"
base64 = "0.10"
parking_lot = "0.9"
jemallocator = { version = "0.3", optional = true }

[dev-dependencies]
log = "0.4"
env_logger = "0.6"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
overflow-checks = true

[[example]]
name = "bogo_shim"
path = "examples/bogo_shim/bogo_shim.rs"
required-features = ["verifier", "error_strings", "tls13", "aesgcm", "chachapoly", "x25519", "ecdh", "ecdsa"]
